async (page) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const check = (condition, message) => { if (!condition) throw new Error(message); };
  const evidence = () => page.evaluate(() => window.workspaceEvidence());
  const card = page.getByRole('article', { name: 'Front Door', exact: true });
  const cameraButton = name => page.getByRole('navigation', { name: 'Camera selection' }).getByRole('button', { name: new RegExp(`^${name}`) });
  check((await evidence()).snapshots.every(name => name === 'Front Door'), 'Only selected preview should refresh');
  await card.getByRole('textbox', { name: 'Message', exact: true }).fill('Please leave the parcel by the door.');
  await card.getByRole('button', { name: 'Describe', exact: true }).click();
  await cameraButton('Backyard').click();
  await page.waitForTimeout(700);
  check(!(await page.getByRole('article', { name: 'Backyard', exact: true }).innerText()).includes('Last action'), 'Results must stay with the requesting camera');
  await cameraButton('Front Door').click();
  await card.getByText('Last action · Describe', { exact: true }).waitFor();
  check((await evidence()).actions.filter(action => action.path === '/api/describe/jobs').length === 1, 'Describe should start once');
  check((await evidence()).polls.length >= 6, 'Describe uses short status reads through all stages');
  check(await card.locator('dt').count() === 6, 'Retain all stages, including zero; deduplicate snapshot timing');
  await page.waitForTimeout(5100);
  check(await card.getByText('Last action · Describe', { exact: true }).isVisible(), 'Result should survive transient feedback');
  const layouts = [];
  for (const width of [1440, 1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    const boxes = await card.evaluate(node => {
      const box = selector => { const r = node.querySelector(selector).getBoundingClientRect(); return { x: r.x, y: r.y, right: r.right, bottom: r.bottom }; };
      return { preview: box('.workspace-preview'), compose: box('.workspace-compose'), output: box('.workspace-output'), tools: box('.workspace-tools'), overflow: document.documentElement.scrollWidth > innerWidth };
    });
    check(!boxes.overflow, `Horizontal overflow at ${width}px`);
    if (width >= 1024) check(boxes.compose.right <= boxes.preview.x && boxes.output.y >= boxes.preview.bottom, `Desktop columns at ${width}px`);
    else check(boxes.compose.y >= boxes.preview.bottom && boxes.output.y >= boxes.compose.bottom && boxes.tools.y >= boxes.output.bottom, `Mobile stack at ${width}px`);
    const action = await card.locator('[data-primary-action]').boundingBox();
    check(width >= 1024 ? action.height <= 36 : action.height >= 44, `Action sizing at ${width}px`);
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: `output/playwright/workspace-${width}.png`, fullPage: true });
    layouts.push({ width, ...boxes });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await card.getByRole('button', { name: 'Hide Front Door preview' }).click();
  const before = (await evidence()).snapshots.length;
  await page.waitForTimeout(2200);
  check((await evidence()).snapshots.length === before, 'Hidden preview should not refresh');
  await page.getByRole('button', { name: 'Next camera', exact: true }).click();
  await page.getByRole('img', { name: 'Backyard preview', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Previous camera', exact: true }).click();
  check(await card.getByRole('button', { name: 'Show Front Door preview' }).isVisible(), 'Preview preference should survive selection');
  await card.getByRole('button', { name: 'Show Front Door preview' }).click();
  await card.getByRole('group', { name: 'Audio source' }).getByRole('button', { name: 'Speak', exact: true }).click();
  check(await card.getByRole('textbox', { name: 'Message', exact: true }).inputValue() === 'Please leave the parcel by the door.', 'Message draft survives Describe and selection');
  await card.locator('[data-primary-action]').click();
  await card.getByText('Last action · Speak', { exact: true }).waitFor();
  await card.getByRole('button', { name: 'Presets', exact: true }).click();
  await card.getByRole('combobox', { name: 'Preset', exact: true }).selectOption(JSON.stringify(['Messages', 'Dinner is ready']));
  await card.locator('summary').filter({ hasText: 'Repeat:' }).click();
  await card.getByLabel('Additional repeats').fill('4');
  await card.locator('[data-primary-action]').click();
  await card.getByText('Last action · Preset · Dinner is ready', { exact: true }).waitFor();
  check((await evidence()).actions.at(-1).body.loop === 4, 'Preserve custom repeat count');
  await card.getByRole('button', { name: 'Pause Front Door', exact: true }).click();
  await card.getByRole('button', { name: 'Resume Front Door', exact: true }).click();
  await card.locator('summary').filter({ hasText: 'Preview here' }).click();
  await page.waitForTimeout(250);
  check(await card.getByRole('region', { name: 'Front Door Camera Output' }).getByRole('meter').getAttribute('aria-valuenow') === '60', 'Output VU reflects reported levels');
  check(await card.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Local waveform preview fits mobile');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'output/playwright/workspace-preset-mobile.png', fullPage: true });
  await card.getByRole('region', { name: 'Front Door Camera Output' }).getByRole('button', { name: 'Stop', exact: true }).click();
  await card.locator('summary').filter({ hasText: 'More audio' }).click();
  await card.getByRole('button', { name: 'Streams', exact: true }).click();
  await card.getByLabel('Stream URL', { exact: true }).fill('https://example.com/live.m3u');
  await card.locator('[data-primary-action]').click();
  await card.getByText('Last action · Stream', { exact: true }).waitFor();
  check((await evidence()).actions.at(-1).path === '/api/play-stream', 'Stream endpoint remains available');
  await card.getByRole('button', { name: 'Files', exact: true }).click();
  await card.getByLabel('Audio file URL', { exact: true }).fill('https://example.com/chime.mp3');
  await card.locator('[data-primary-action]').click();
  await card.getByText('Last action · Audio URL', { exact: true }).waitFor();
  check((await evidence()).actions.at(-1).path === '/api/play-url', 'File URL endpoint remains available');
  const result = await evidence();
  check(result.errors.length === 0, `Browser errors: ${result.errors.join(', ')}`);
  return { passed: 'Layout, persistent results, camera drafts, preview lifecycle, TTS, presets, loops, pause/resume/stop, streams and URLs', layouts, actions: result.actions, errors: result.errors };
}
